config.basicSkills = [
  'Aufmerksamkeit',
  'Ausweichen',
  'Befehligen',
  'Charme',
  'Feilschen',
  'Forschender Blick',
  'Glücksspiel',
  'Klettern',
  'Logik',
  'Nachforschen',
  'Schätzen',
  'Schlangenmensch',
  'Schleichen',
  'Schwimmen',
  'Suchen',
  'Tarnung',
  'Verkleiden',
  'Vorgaukeln',
  'Zechen'
]
