config.skills = {
  'Akrobatik' : 'ge',
  'Allgemeinwissen (Adeptus Arbites)' : 'in',
  'Allgemeinwissen (Administratum)' : 'in',
  'Allgemeinwissen (Ekklesiarchie)' : 'in',
  'Allgemeinwissen (Imperiale Armee)' : 'in',
  'Allgemeinwissen (Imperiale Religion)' : 'in',
  'Allgemeinwissen (Imperium)' : 'in',
  'Allgemeinwissen (Krieg)' : 'in',
  'Allgemeinwissen (Maschinenkult)' : 'in',
  'Allgemeinwissen (Tech)' : 'in',
  'Allgemeinwissen (Unterwelt)' : 'in',
  'Anrufung' : 'wk',
  'Aufmerksamkeit' : 'wa',
  'Ausweichen' : 'ge',
  'Befehligen' : 'ch',
  'Beruf (Apotheker)' : 'in',
  'Beruf (Bergmann)' : 'st',
  'Beruf (Einbalsamierer)' : 'in',
  'Beruf (Illustrator)' : 'ge',
  'Beruf (Gerber)' : 'st',
  'Beruf (Graveur)' : 'ge',
  'Beruf (Kartograph)' : 'ge',
  'Beruf (Kaufmann)' : 'ch',
  'Beruf (Koch)' : 'wa',
  'Beruf (Konstrukteur)' : 'in',
  'Beruf (Kopist)' : 'in',
  'Beruf (Landwirt)' : 'st',
  'Beruf (Maurer)' : 'st',
  'Beruf (Page)' : 'ch',
  'Beruf (Prospektor)' : 'st',
  'Beruf (Rüstungsschmied)' : 'st',
  'Beruf (Schmied)' : 'st',
  'Beruf (Steinmetz)' : 'ge',
  'Beruf (Techwart)' : 'in',
  'Beruf (Wahrsager)' : 'ch',
  'Beschatten' : 'ge',
  'Charme' : 'ch',
  'Chem-Gebrauch' : 'in',
  'Fahren (Bodenfahrzeug)' : 'ge',
  'Fahren (Läufer)' : 'ge',
  'Fahren (Schwebefahrzeug)' : 'ge',
  'Feilschen' : 'ch',
  'Fingerfertigkeit' : 'ge',
  'Forschender Blick' : 'wa',
  'Geheimsprache (Administratum)' : 'in',
  'Geheimsprache (Akolythen)' : 'in',
  'Geheimsprache (Ekklesiarchie)' : 'in',
  'Geheimsprache (Gosse)' : 'in',
  'Geheimsprache (Militärjargon)' : 'in',
  'Geheimsprache (Tech)' : 'in',
  'Geheimzeichen (Akolythen)' : 'in',
  'Geheimzeichen (Militär)' : 'in',
  'Geheimzeichen (Okkultisten)' : 'in',
  'Geheimzeichen (Unterwelt)' : 'in',
  'Glücksspiel' : 'in',
  'Klettern' : 'st',
  'Kunst (Erzählen)' : 'ch',
  'Kunst (Gesang)' : 'ch',
  'Kunst (Musik)' : 'ch',
  'Kunst (Tanz)' : 'ch',
  'Lesen/Schreiben' : 'in',
  'Lippenlesen' : 'wa',
  'Logik' : 'in',
  'Medizin' : 'in',
  'Nachforschen' : 'ch',
  'Navigation (Oberfläche)' : 'in',
  'Navigation (Stellar)' : 'in',
  'Pilot (Militär)' : 'ge',
  'Pilot (Raumschiff)' : 'ge',
  'Pilot (Zivil)' : 'ge',
  'Psi-Gespür' : 'wa',
  'Redeschwall' : 'ch',
  'Schätzen' : 'in',
  'Schlangenmensch' : 'ge',
  'Schleichen' : 'ge',
  'Scholastisches Wissen (Archaik)' : 'in',
  'Scholastisches Wissen (Astromantie)' : 'in',
  'Scholastisches Wissen (Bürokratie)' : 'in',
  'Scholastisches Wissen (Chymie)' : 'in',
  'Scholastisches Wissen (Flora)' : 'in',
  'Scholastisches Wissen (Heraldik)' : 'in',
  'Scholastisches Wissen (Imperiale Religion)' : 'in',
  'Scholastisches Wissen (Jura)' : 'in',
  'Scholastisches Wissen (Kryptologie)' : 'in',
  'Scholastisches Wissen (Legenden)' : 'in',
  'Scholastisches Wissen (Numerologie)' : 'in',
  'Scholastisches Wissen (Okkultismus)' : 'in',
  'Scholastisches Wissen (Philosophie)' : 'in',
  'Scholastisches Wissen (Tactica Imperialis)' : 'in',
  'Scholastisches Wissen (Tiere)' : 'in',
  'Schwimmen' : 'st',
  'Sicherheit' : 'ge',
  'Sprache (Hochgotisch)' : 'in',
  'Sprache (Makropoldialekt)' : 'in',
  'Sprache (Niedergotisch)' : 'in',
  'Sprache (Schiffsdialekt)' : 'in',
  'Sprache (Stammesdialekt)' : 'in',
  'Sprengstoffgebrauch' : 'in',
  'Spuren lesen' : 'in',
  'Suchen' : 'wa',
  'Tarnung' : 'ge',
  'Tech-Gebrauch' : 'in',
  'Überleben' : 'in',
  'Umgang mit Tieren' : 'in',
  'Vebotenes Wissen (Adeptus Mechanicus)' : 'in',
  'Vebotenes Wissen (Archäotechnik)' : 'in',
  'Vebotenes Wissen (Dämonologie)' : 'in',
  'Vebotenes Wissen (Inquisition)' : 'in',
  'Vebotenes Wissen (Ketzerei)' : 'in',
  'Vebotenes Wissen (Kulte)' : 'in',
  'Vebotenes Wissen (Mutanten)' : 'in',
  'Vebotenes Wissen (Ordo Hereticus)' : 'in',
  'Vebotenes Wissen (Ordo Malleus)' : 'in',
  'Vebotenes Wissen (Ordo Xenos)' : 'in',
  'Vebotenes Wissen (Psioniker)' : 'in',
  'Vebotenes Wissen (Schwarze Bibliothek)' : 'in',
  'Vebotenes Wissen (Warp)' : 'in',
  'Vebotenes Wissen (Xenos)' : 'in',
  'Verhör' : 'wk',
  'Verkleiden' : 'ch',
  'Vorgaukeln' : 'ch',
  'Zechen' : 'wi'
}
